version: "3"

services:

  customerdata:
    image: postgres:11.5
    networks:
      - shopnet
    volumes:
      - customerdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    container_name: customer
    build: .
    volumes:
      - .:/code:cached

    # The command to be run when we run "docker-compose up".
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    # Expose port 3000.
    ports:
      - "3000:3000"
    networks:
      - shopnet
    # Specify that this container depends on the other
    # container called "customerdata".
    depends_on:
      - customerdata

    # Specify the values of the environment variables
    # used in this container.
    environment:
      RAILS_ENV: development
      DATABASE_NAME: customers_development
      DATABASE_USER: customer_development
      DATABASE_PASSWORD:
      DATABASE_HOST: customer-data

# Declare the volumes that our application uses.
volumes:
  customerdata:
networks:
  shopnet: